### ISSUE TITLE
Journald is broken in sid

### ISSUE THREAD

**Issue by arjun0987** [scaleway/image-debian#71] opened 2016-08-09 13:40 UTC
Upstream bug report: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=832713

**Comment by kellogs** [comment] 2016-10-29 11:28
Confirmed. SID is completely broken because of lack of Journald.

**Comment by myier** [comment] 2016-10-30 00:31
Check [this](https://community.online.net/t/c1-arch-not-starting-journal/2856/3) out.
I just installed a C1, did the machine-id trick, removed exim4 just in case, apt-get upgraded to stretch (not sid) and I was able to reboot and still have a server (what a nice feature!).

**Comment by rhertzog** [comment] 2017-06-27 10:09
So the problem is that /etc/machine-id contains two lines (the first line is always the same 32 bit ID for me: 2c0771634a3144059497699f79981f6b, the second line is 3 random characters). That file should only contain a single line and the presence of that second line is breaking systemd-journal.service and a few others:

```
# cat /etc/machine-id 
2c0771634a3144059497699f79981f6b
eab
# systemctl list-units --state failed
  UNIT                               LOAD   ACTIVE SUB    DESCRIPTION                              
● systemd-journald.service           loaded failed failed Journal Service                          
● systemd-tmpfiles-setup-dev.service loaded failed failed Create Static Device Nodes in /dev       
● systemd-tmpfiles-setup.service     loaded failed failed Create Volatile Files and Directories    
● systemd-journald-audit.socket      loaded failed failed Journal Audit Socket                     
● systemd-journald-dev-log.socket    loaded failed failed Journal Socket (/dev/log)                
● systemd-journald.socket            loaded failed failed Journal Socket        
```

Fixing that file helps a bit but not for long as /etc/machine-id is overwritten on next boot. This is a really annoying problem that ought to be fixed quickly.

But looking at /usr/local/sbin/scw-gen-machine-id, it should do nothing when /etc/.regen-machine-id does not exist. Yet I get the bug on each "hard reboot" (soft reboot is currently failing). And when I look into https://github.com/scaleway/initrd/blob/master/Linux/tree-common/init#L446 I see nothing else than a call to this file. So I really wonder what's going on.

For the record, I used a sid base image for a C1 server and I'm using the "armv7l 4.9.20 std #1 (longterm/latest)" kernel/initrd combination.

**Comment by rhertzog** [comment] 2017-06-27 10:30
The fixed machine-id is actually the same as the value that I have in /var/lib/dbus/machine-id. It's probably hardcoded in the base image (while it should not).

**Comment by frivoire** [comment] 2017-06-29 15:29
We have improved the handling of machine-id  (removing it from base image and regenerate it on first launch),
cf: https://github.com/scaleway/image-tools/commit/a0a2e37adde958200d5db089c0f3517de502bf45

Here is an example of the result (freshly created instance, with patched image) :
```
# cat /etc/machine-id
b5d6cf202d6c2b9e69662b9259551b7d
# systemctl list-units --state failed
0 loaded units listed. Pass --all to see loaded but inactive units, too.
To show all installed unit files use 'systemctl list-unit-files'.
```

New sid images are building with this fix.
We'll update this issue when they are published.

**Comment by rhertzog** [comment] 2017-06-29 18:16
@frivoire Thanks, will you roll new boot scripts (i.e. kernel+initrd) as well? Because something must be fishy there as /etc/machine-id is overwritten on each boot currently for me and I'd like to get it fixed without starting from a fresh image.

**Comment by frivoire** [comment] 2017-06-30 09:08
@rhertzog : I've created a C1 test instance :
- with the "old" sid image (armv7l-debian-sid-2016-04-06_15:24)
- and bootscript "armv7l 4.9.20 std #1 (longterm/latest)"

And here is the result :
```
ssh root@
# cat /etc/machine-id
2c0771634a3144059497699f79981f6b
d3b
# vi /etc/machine-id
[manually remove the buggy 2nd line]
# sync
# cat /etc/machine-id
2c0771634a3144059497699f79981f6b
[hard reboot]
# cat /etc/machine-id
2c0771634a3144059497699f79981f6b
```

So, as you can see, I can't reproduce the behaviour of "machine-id is overwritten on each boot".
Do you have precise steps that could allow us to reproduce ?

**Comment by rhertzog** [comment] 2017-06-30 10:14
@frivoire Hum, I tried again and I can no longer reproduce it. Weird.

At some point, I tried to boot once with "/etc/.regen-machine-id" to force the execution of scw-gen-machine-id, maybe it was related and the file did not get properly deleted on first reboot. Anyway, thanks for your help!

**Comment by frivoire** [comment] 2017-07-03 08:23
We have released the fixed sid images.

**Closed by frivoire** 2017-07-03 08:23 UTC
