### ISSUE TITLE
scw-sync-kernel-modules not always called

### ISSUE THREAD

**Issue by mazarini** [scaleway/image-debian#58] opened 2016-03-19 21:35 UTC
Hi,

Since february, 18,  /lib/modules is empty when creating a Jessie server. I use 4.4.4-std-3 kernel.

I see it using openvpn  (/lib/modules/4.4.4-std-3/kernel/drivers/net/tun.ko)
(copy all from an older server to continue).

**Comment by moul** [comment] 2016-03-21 11:31
Hi @mazarini,

What is your architecture ? arm or x86_64 ?

I just checked and the mirror seems to have the files here for x86_64: http://mirror.scaleway.com/kernel/x86_64/4.4.4-std-3/

---

Can you run this script and paste the result here ?

```shell
mv /lib/modules /lib/modules.old
bash -x /usr/local/sbin/oc-sync-kernel-modules
```

**Comment by Ivshti** [comment] 2016-03-21 12:33
@moul I just ran that and it fixed the issue for me

I was trying to use iptables

**Comment by moul** [comment] 2016-03-21 14:31
@Ivshti, ok,

The script should run automatically at boot, I will investigate,

Which image did you ran ? Debian Jessie ? Debian Wheezy ? Debian Sid ? other ?

**Comment by Ivshti** [comment] 2016-03-21 14:36
@moul Sid

**Comment by mazarini** [comment] 2016-03-21 17:34
Hi moul,
Just come from work...

`root@service:~# ls -l /lib/modules
total 0
root@service:~# ` 

`root@service:~# uname -a
Linux service.riva.link 4.4.4-std-3 #1 SMP Tue Mar 8 17:31:34 UTC 2016 x86_64 GNU/Linux
root@service:~# `

`root@service:~# hostnamectl 
   Static hostname: service.riva.link
         Icon name: computer-vm
           Chassis: vm
           Boot ID: 26230f7ed0624ed583da4d10f89a684e
    Virtualization: kvm
  Operating System: Debian GNU/Linux 8 (jessie)
            Kernel: Linux 4.4.4-std-3
      Architecture: x86-64
root@service:~# `

`root@service:~# bash -x /usr/local/sbin/oc-sync-kernel-modules
+ set -e
+ DIR=/lib/modules
+ mkdir -p /lib/modules
++ mktemp -d -p /lib/modules
+ TMP_DIR=/lib/modules/tmp.v4guKHK9m7
++ uname -r
+ KVERSION=4.4.4-std-3
++ uname -m
+ KARCH=x86_64
+ TIMEOUT=10
+ export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/bin:/bin:/usr/local/bin:/sbin:/usr/sbin:/usr/local/sbin
+ PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/bin:/bin:/usr/local/bin:/sbin:/usr/sbin:/usr/local/sbin
+ trap clean INT TERM EXIT
+ '[' '!' -d /lib/modules/4.4.4-std-3 ']'
+ wget --timeout=10 --quiet --no-check-certificate -r --no-parent --reject 'index.html*' --reject robots.txt --no-host-directories --cut-dirs 4 --directory-prefix /lib/modules/tmp.v4guKHK9m7 http://mirror.scaleway.com/kernel/x86_64/4.4.4-std-3/modules/4.4.4-std-3/
+ clean
+ rm -rf /lib/modules/tmp.v4guKHK9m7
root@service:~# 
`
Nothing better
`root@service:~# ls -l /lib/modules
total 0
root@service:~# 
`

**Comment by moul** [comment] 2016-03-21 17:51
@mazarini, ok I think the recent [update](https://github.com/scaleway/image-tools/blob/master/skeleton-common/usr/local/sbin/scw-sync-kernel-modules) of the scw-sync-kernel-modules broke compatibility with older images

Can you try to update the script itself and run it again:

```bash
wget https://raw.githubusercontent.com/scaleway/image-tools/master/skeleton-common/usr/local/sbin/scw-sync-kernel-modules -O /usr/local/sbin/scw-sync-kernel-modules

chmod +x /usr/local/sbin/scw-sync-kernel-modules

rm -rf /lib/modules

bash -x usr/local/sbin/scw-sync-kernel-modules
```

**Comment by mazarini** [comment] 2016-03-21 18:17
May be it's me the problem. Not a bug.
I have no public IP : raw.githubusercontent.com is not accessible
I drop all except from one IP and accept only port 53 from all (security group)

I try to open 80 and 443 from all in security group and post the result.

**Comment by moul** [comment] 2016-03-21 18:19
ok, if the issue is the security groups, we should add an hardcoded rules before your security group rules to always allow access to the mirror

**Comment by mazarini** [comment] 2016-03-21 19:30
I just build a new server with default security group and no public IP.
Modules are OK but use 4.4.6-std-2 and not 4.4.4-std-3 as previously (still Debian Jessie). 
`root@scw-36c4ab:~# uname -a`
`Linux scw-36c4ab 4.4.6-std-2 #1 SMP Mon Mar 21 13:41:00 UTC 2016 x86_64 GNU/Linux`
`root@scw-36c4ab:~# `

Can't you tell me : 
 - which IP/protocol/port open to have modules (before you modify security group)
 - how is update kernel or how to know when reboot to get update.

Note I like to have an image package from a scaleway's repository. So no problem to update and to know when update. Probably  without kernel, may be just a dummy package to tell me I have to reboot.

**Comment by moul** [comment] 2016-03-22 11:31
> which IP/protocol/port open to have modules (before you modify security group)

We will update our rules so you can successfully boot your server even with "DROP *" rules in your SG

For now, you can try to force allow TCP from 169.254.42.42 and 169.254.42.24 (metadata + mirror)
And allow UDP from the dns server (ip varies depending on your node location, so for now, allow UDP 53 from everywhere)

> how is update kernel or how to know when reboot to get update.

we are building new kernels regularly, last ones were built yesterday, we will add some new ones probably tomorrow and update the existing one in about a week

there is not notification system for this as we are deploying new kernels very often, the "old" ones are never old enough to be considered as unsafe, however, this repo contains configuration of each kernels (https://github.com/scaleway/kernel-tools), you can already subscribe to the repo notifications and ping me if a recent feature is important for you, so I can run the build&release process quickly

If you have suggestions about the way we can notify people about new kernel releases, I'm interested by your feedback

> Extra request : allow re-install a server. ActualIy create un new server and put the disk on a older to keep the id.

I like the idea, do you have a more complete scenario to give me as an example ?

**Comment by mazarini** [comment] 2016-03-22 21:20
About re-install : 
1) add a button "Reinstall" for server without disk (more secure again bad/mis action)
2) use the same page than create but initialyse with the datas from server (server id and name, network, image or snapshot, security group.
I like to keep the id and so keep server name (xxxxx.priv.cloud.scaleway.com). Keep other datas will be bonus.

**Comment by moul** [comment] 2016-03-23 10:37
@mazarini, interesting, we will look how we can add something like this

For now, I have a workflow that may fit your needs (not as simple as the one you described), but it may allow you to preserve your server UUID while updating the rootfs.

warn: this is an advanced usage, you should backup your important data before trying one of the following methods

---

#### Method 1 (using rescue):

1. [Switch](https://www.scaleway.com/docs/bootscript-and-how-to-use-it/) to the **rescue** bootscript
2. Reboot your server, from command line or browser, but don't stop/terminate it (to keep the same node).
3. The server will reboot in rescue (another rootfs loaded in ramfs), here you can mount your disk (/dev/vda for VPS, /dev/nbd0 for other servers), clean it completely, and write another image, [here](http://store-travis.scw.42.am/travis/images/) are the some of the Scaleway images in a tarball format, so you can download and untar the contents in the mounted rootfs to get a fresh new volume, using this method, your are not limited to tarball, you can probably download a .iso disk for instance
4. Switch back to your non-rescue bootscript
5. Reboot 
6. Done

---

#### Method 2 (semi-automated but limited to tarballs):

1. Add these tags to your server: `boot=live`, `live_mode=install`, `rescue_image=http://store-travis.scw.42.am/travis/images/x86_64-ubuntu-wily.tar` (or another tarball URL)
2. Reboot
3. Done, your server will boot with the content of the tarball written on the disk
4. Don't forget to remove the server tags to avoid reinstalling the rootfs on the next boot :)

**Comment by mazarini** [comment] 2016-03-23 13:27
### Simple method (noob usage)
1.   stop/archive server
2.   detach disk and destroy it
3.   create new server
4.   stop/archive new server
5.   destroy new server (new public IP and new disk are keep)
6.   attach new disk to server
7.   destroy new public ip
8.   start server (with fresh install on new disk)

**Comment by moul** [comment] 2016-03-23 13:28
yep!

just note, this way you will keep your server UUID but not its node location

**Comment by mazarini** [comment] 2016-03-23 13:42
I assume I have only short property on private IP (= location ?). 
I base network on my dns server using cname on "id".priv.cloud.scaleway.com and openvpn. But still in work for dns.

**Comment by moul** [comment] 2016-03-23 14:27
yep, you're totally right

**Comment by moul** [comment] 2016-03-23 14:27
Closing this issue for now, if it happens again, just reopen it :)

**Closed by moul** 2016-03-23 14:27 UTC
Labels: bug
